# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9243ea086f66db01c56dbc7dc7cd8069f95517f8ae22e72d5ae7875fe016ba50e8580e28195e0cfdedc4b1515d39b5ed15942bdf463ba3b7fc6bc414562b3137

test:
  secret_key_base: ff3793c433081452ee43ba8a97a4eacc53143ad70d0d3ef2846973318aa6f78bc73056d0c3e5152dfd9d9b607fcaa3b4c6b4d569992bf93c7907b8ae8128fc89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
